labels:
  - name: verified
    labeled:
      issue:
        body: |
          * [x] - The plugin must successfully install.
          * [x] - The plugin must implement the Homebridge Plugin Settings GUI.
          * [x] - The plugin must not start unless it is configured.
          * [x] - The plugin must not execute post-install scripts that modify the user's system in any way.
          * [x] - The plugin must not contain any analytics or calls that enable you to track the user.
          * [x] - The plugin must not throw unhandled exceptions, the plugin must catch and log its own errors.
          * [x] - The plugin must be published to npm and the source code available on GitHub.
          * [x] - GitHub releases should be created for every new version of your plugin, with patch notes.
          * [x] - The plugin must run on all Active LTS versions of Node.js, at the time of writing this is Node.js v14 and v16.
          * [x] - The plugin must not require the user to run Homebridge in a TTY or with non-standard startup parameters, even for initial configuration.
          * [x] - If the plugin needs to write files to disk (cache, keys, etc.), it must store them inside the Homebridge storage directory.

          ---

         Everything Looks Good!
labels:
  - name: verified
    labeled:
      issue:
        body: |
          Congratulations! Your plugin has been verified.

          You can now add the *Verified by Homebridge* badge to your plugin's README:

          [![verified-by-homebridge](https://badgen.net/badge/homebridge/verified/purple)](https://github.com/homebridge/homebridge/wiki/Verified-Plugins)

          ```
          [![verified-by-homebridge](https://badgen.net/badge/homebridge/verified/purple)](https://github.com/homebridge/homebridge/wiki/Verified-Plugins)
          ```

          Your plugin is now also eligible to display a *:heart: Donate* button on it's tile in the Homebridge UI. See https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Donation-Links for instructions.

          Thank you for your contribution to the Homebridge Community.
          https://homebridge.io
labels:
  - name: awaiting-changes
    labeled:
      issue:
        body: |
          * [ ] - The plugin must successfully install.
          * [ ] - The plugin must implement the Homebridge Plugin Settings GUI.
          * [ ] - The plugin must not start unless it is configured.
          * [ ] - The plugin must not execute post-install scripts that modify the user's system in any way.
          * [ ] - The plugin must not contain any analytics or calls that enable you to track the user.
          * [ ] - The plugin must not throw unhandled exceptions, the plugin must catch and log its own errors.
          * [ ] - The plugin must be published to npm and the source code available on GitHub.
          * [ ] - GitHub releases should be created for every new version of your plugin, with patch notes.
          * [ ] - The plugin must run on all Active LTS versions of Node.js, at the time of writing this is Node.js v14 and v16.
          * [ ] - The plugin must not require the user to run Homebridge in a TTY or with non-standard startup parameters, even for initial configuration.
          * [ ] - If the plugin needs to write files to disk (cache, keys, etc.), it must store them inside the Homebridge storage directory.

          ---

         ```

         ```          
