labels:
  - name: reviewed
    labeled:
      issue:
        body: |
          * [x] - The plugin must successfully install.
          * [x] - The plugin must implement the Homebridge Plugin Settings GUI.
          * [x] - The plugin must not start unless it is configured.
          * [x] - The plugin must be of type dynamic platform.
          * [x] - The plugin must not offer the same nor less functionality than that of any existing verified plugin.
          * [x] - The plugin must not execute post-install scripts that modify the user's system in any way.
          * [x] - The plugin must not contain any analytics or calls that enable you to track the user.
          * [x] - The plugin must not throw unhandled exceptions, the plugin must catch and log its own errors.
          * [x] - The plugin must be published to npm and the source code available on GitHub.
          * [x] - A GitHub release should be created for every new version of your plugin, with patch notes.
          * [x] - The plugin must run on all Active LTS versions of Node.js, at the time of writing this is Node v18 and v20.
          * [x] - The plugin must not require the user to run Homebridge in a TTY or with non-standard startup parameters, even for initial configuration.
          * [x] - If the plugin needs to write files to disk (cache, keys, etc.), it must store them inside the Homebridge storage directory.

          ---

          Everything Looks Good!
        action: open
  - name: verified
    labeled:
      issue:
        body: |
          Congratulations! Your plugin has been verified.

          You can now add one of the *Verified by Homebridge* badges to your plugin's README:

          [![verified-by-homebridge](https://badgen.net/badge/homebridge/verified/purple)](https://github.com/homebridge/homebridge/wiki/Verified-Plugins)

          ```
          [![verified-by-homebridge](https://badgen.net/badge/homebridge/verified/purple)](https://github.com/homebridge/homebridge/wiki/Verified-Plugins)
          ```
          
          [![verified-by-homebridge](https://img.shields.io/badge/homebridge-verified-blueviolet?color=%23491F59&style=for-the-badge&logoColor=%23FFFFFF&logo=homebridge)](https://github.com/homebridge/homebridge/wiki/Verified-Plugins)
  
          ```
          [![verified-by-homebridge](https://img.shields.io/badge/homebridge-verified-blueviolet?color=%23491F59&style=for-the-badge&logoColor=%23FFFFFF&logo=homebridge)](https://github.com/homebridge/homebridge/wiki/Verified-Plugins)
          ```

          Your plugin is now also eligible to display a *:heart: Donate* button on its tile in the Homebridge UI. See https://github.com/homebridge/homebridge/wiki/Donation-Links for instructions.

          If for any reason in the future you can no longer maintain your plugin, please consider transferring it to our [unmaintained plugins repo](https://github.com/homebridge/unmaintained-plugins). We can take ownership until another willing developer comes along.

          Don't forget to join the official [Homebridge Discord server](https://discord.gg/A7nCjbz), where plugin developers can get tips and advice from other developers and the Homebridge project team in the #plugin-development channel!

          Thank you for your contribution to the Homebridge Community.
          https://homebridge.io
        action: open
  - name: currently-reviewing
    labeled:
      issue:
        body: |
          * [ ] - The plugin must successfully install.
          * [ ] - The plugin must implement the Homebridge Plugin Settings GUI.
          * [ ] - The plugin must not start unless it is configured.
          * [ ] - The plugin must be of type dynamic platform.
          * [ ] - The plugin must not offer the same nor less functionality than that of any existing verified plugin.
          * [ ] - The plugin must not execute post-install scripts that modify the user's system in any way.
          * [ ] - The plugin must not contain any analytics or calls that enable you to track the user.
          * [ ] - The plugin must not throw unhandled exceptions, the plugin must catch and log its own errors.
          * [ ] - The plugin must be published to npm and the source code available on GitHub.
          * [ ] - A GitHub release should be created for every new version of your plugin, with patch notes.
          * [ ] - The plugin must run on all Active LTS versions of Node.js, at the time of writing this is Node v18 and v20.
          * [ ] - The plugin must not require the user to run Homebridge in a TTY or with non-standard startup parameters, even for initial configuration.
          * [ ] - If the plugin needs to write files to disk (cache, keys, etc.), it must store them inside the Homebridge storage directory.

          ---

          ```

          ```
          
          ---
          #### Comment `/check` to run checks again.
        action: open
