name: Plugin Transfer Request
description: Request to transfer your plugin into the Homebridge Plugins organization for a scoped plugin.
title: 'Transfer Request: homebridge-'
labels:
  - request-transfer
body:
  - type: markdown
    attributes:
      value: '## Basic Details'
  - type: markdown
    attributes:
      value: |
        - You must be the developer of the plugin to request the transfer.
        - You must be willing to transfer the NPM package to the Homebridge organization.
        - You will be granted admin access to the GitHub repository, and write access to the NPM package.
        - Your plugin will be published under the Homebridge Plugins organization on NPM (@homebridge-plugins/homebridge-xyz).
  - type: input
    id: plugin-name
    attributes:
      label: Plugin Name
      description: The name of your plugin as it appears on NPM. For example `homebridge-xyz` or `@scope/homebridge-xyz`.
      placeholder: homebridge-xyz
    validations:
      required: true
  - type: input
    attributes:
      label: NPM Username
      placeholder: npm-user
    validations:
      required: true
  - type: input
    attributes:
      label: Link To GitHub Repo
      placeholder: https://github.com/homebridge/homebridge-xyz
    validations:
      required: true
  - type: markdown
    attributes:
      value: '## Maintenance'
  - type: markdown
    attributes:
      value: |
        If you select yes to the following question, then:
        - We will not list the plugin as unmaintained
        - We will not give other developers maintainer access to the plugin

        If you select no to the following question, then:
        - We will list the plugin as unmaintained
        - We may accept requests from other developers to become maintainers of the plugin

        Either way, the plugin will not be transferred out of the Homebridge Plugins organization.
  - type: dropdown
    attributes:
      label: Do you plan to continue maintaining the plugin?
      options:
        - Yes - I will continue to maintain the plugin
        - No - I will not continue to maintain the plugin
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Are you requesting a `@homebridge-plugins/` scope for this plugin?
      options:
        - Yes - I am requesting a @homebridge-plugins/ scope for this plugin
        - No - I am not requesting a @homebridge-plugins/ scope for this plugin
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: '## More Information'
  - type: textarea
    attributes:
      label: More Information
      description: Please provide any additional information that you want to include.
