name: Plugin Transfer Request
description: Request to transfer your plugin into Homebridge ownership.
title: 'Transfer Request: homebridge-'
labels:
  - request-transfer
body:
  - type: markdown
    attributes:
      value: '## Basic Details'
  - type: markdown
    attributes:
      value: |
        - You must be the developer of the plugin to request the transfer.
        - You must be willing to transfer the GitHub repository to the Homebridge Plugins organization.
        - You must be willing to transfer the NPM package to the Homebridge organization.
        - Another developer may request to maintain the plugin.
  - type: input
    id: plugin-name
    attributes:
      label: Plugin Name
      description: The name of your plugin as it appears on NPM. For example `homebridge-xyz` or `@scope/homebridge-xyz`.
      placeholder: homebridge-xyz
    validations:
      required: true
  - type: input
    attributes:
      label: Link To GitHub Repo
      placeholder: https://github.com/homebridge/homebridge-xyz
    validations:
      required: true
  - type: markdown
    attributes:
      value: '## More Information'
  - type: textarea
    attributes:
      label: More Information
      description: Please provide any additional information that you want to include.
