name: Plugin Maintain Request
description: Request to maintain a Homebridge plugin that has been listed as unmaintained.
title: 'Maintain Request: homebridge-'
labels:
  - request-maintain
body:
  - type: markdown
    attributes:
      value: '## Basic Details'
  - type: markdown
    attributes:
      value: |
        - The GitHub repository will remain in the Homebridge Plugins organization.
        - You will be granted admin access to the GitHub repository, and maintainer access to the NPM package.
  - type: input
    id: plugin-name
    attributes:
      label: Plugin Name
      description: The name of the plugin you would like to maintain.
      placeholder: homebridge-xyz
    validations:
      required: true
  - type: textarea
    attributes:
      label: References
      description: References to other plugins you have developed or have helped maintain.
