name: Issue Labeler
on:
  issue_comment:
    types:
      - created
jobs:
  review_add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.comment.body, '/check') && contains(github.event.issue.labels.*.name, 'request-verification') }}
        with:
          labels: pending
  review_remove_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ startsWith(github.event.comment.body, '/check') && contains(github.event.issue.labels.*.name, 'request-verification') }}
        with:
          github_token: ${{ secrets.github_token }}
          labels: |
            awaiting-changes
            awaiting-user-reply
            verified
            currently-reviewing
