name: Issue Labeler
on:
  issue_comment:
    types:
      - created
permissions:
  issues: write

jobs:
  review_add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Check if comment starts with /check
        id: check-command
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          FIRST_LINE=$(echo "$COMMENT_BODY" | head -n 1 | tr -d ' \t\r')
          if [[ "$FIRST_LINE" == "/check" ]]; then
            echo "is_check_command=true" >> $GITHUB_OUTPUT
          else
            echo "is_check_command=false" >> $GITHUB_OUTPUT
          fi
      - uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf # v1
        if: ${{ steps.check-command.outputs.is_check_command == 'true' && contains(github.event.issue.labels.*.name, 'request-verification') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: pending
  review_remove_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Check if comment starts with /check
        id: check-command
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          FIRST_LINE=$(echo "$COMMENT_BODY" | head -n 1 | tr -d ' \t\r')
          if [[ "$FIRST_LINE" == "/check" ]]; then
            echo "is_check_command=true" >> $GITHUB_OUTPUT
          else
            echo "is_check_command=false" >> $GITHUB_OUTPUT
          fi
      - uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0 # v1
        if: ${{ steps.check-command.outputs.is_check_command == 'true' && contains(github.event.issue.labels.*.name, 'request-verification') }}
        with:
          github_token: ${{ secrets.github_token }}
          labels: |
            awaiting-changes
            awaiting-user-reply
            verified
            currently-reviewing
