name: Label Commenter
on:
  issues:
    types:
      - labeled
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Label Commenter
        if: ${{ contains(github.event.issue.labels.*.name, 'request-verification') }}
        uses: peaceiris/actions-label-commenter@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/label-commenter-config.yml
