name: Plugin Tarballs

on:
  workflow_dispatch:
  schedule:
    - cron: '47 12 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: v24
      - name: Install Dependencies & Build
        run: npm install && npm run plugin-tarballs:build
      - name: Plugin Tarball Maintenance
        run: npm run plugin-tarballs:run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
