name: Plugin Checks (Schedule)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  check-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies & Build
        run: npm install && npm run plugin-checks:build
      - name: Randomly Select Plugin
        id: get-verified-plugin
        run: |
          plugin=$(jq -r 'to_entries | map(select(.value.verified == true)) | .[].key' assets/plugins.json | shuf -n 1)
          echo "plugin=$plugin" >> $GITHUB_ENV
        shell: bash
      - name: Check Plugin
        uses: ./src/plugin-checks
        with:
          plugin: ${{ env.plugin }}
