name: Plugin Tarballs

on:
  workflow_dispatch:
  schedule:
    - cron: '47 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: v20
      - name: Install Dependencies & Build
        run: npm install && npm run plugin-tarballs:build
      - name: Plugin Tarball Maintenance
        run: npm run plugin-tarballs:run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: gautamkrishnar/keepalive-workflow@v2
